version: "3.9"

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=gyakuten
    volumes:
      - gyakuten_pg_data:/bitnami/postgresql

volumes:
  gyakuten_pg_data:
